version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: ai-backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/text_to_video
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    command: npm run dev
    volumes:
      - ./Backend:/app
      - /app/node_modules

  worker:
    build: ./Worker
    container_name: ai-worker
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/text_to_video
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./Worker:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: ai-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: ai-redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
